### ISSUE TITLE
Large RTK position covariance values

### ISSUE THREAD

**Issue by rokusottervanger** [swift-nav/swiftnav_ros#2]
I'm trying the RTK setup, and I'm getting an odometry message with the following pose covariance:
```
covariance: [555025000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 555025000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1595169000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0]
```
I would expect the (x, x) and (y, y) elements of the to be in the order of magnitude of 1.0 m^2 or smaller. Is this a bug? Any ideas on how to fix this? I'd be happy to shoot a PR.

**Comment by denniszollo** [comment]
Thank you for reporting.  I have a few questions to help diagnose.

- Can you provide more information about the receiver state just prior to the issue? 
- How was your receiver configured and where was the antenna placed?
- Do you have a snippet of the ROS log or ROS bag at the time? 
- Does this happen all the time or just during one test?
- What type of computer and architecture are you using?

In looking over the covariance output here: https://github.com/swift-nav/swiftnav_ros/blob/master/src/swiftnav_ros_driver.cpp#L225 , everything looks in order. 

Thanks in advance for your response!

**Comment by rokusottervanger** [comment]
- The GPS antenna is placed on top of our rover robot, the radio antenna as well. The base station GPS antenna is mounted on a tripod, and its radio antenna is mounted on the side of a box containing the base station boards and power source. [Here](https://photos.app.goo.gl/MWzgOvPpSjXW7pEW2) are some photos for reference.
 - Base station and receiver were configured as instructed in the [getting started guide for RTK positioning](https://support.swiftnav.com/customer/en/portal/articles/2771177-piksi-multi---rtk-position)
 - [Here](https://drive.google.com/file/d/1JD-X4b4GLgTv3DpapgVN_nStkZLMqN2E/view?usp=sharing) is a link to a ROS bag file with the issue.
 - This happens all the time. Or at least, I have not seen it NOT occurring yet.
 - The computer uses an Intel I7 processor, with 8GB of memory and 64 bit Ubuntu server installed. 
Thanks for your help!
